- test/test-server-creation.js
During PR review, appmetrics was changed to no longer be mandatory as an
option, but the tests were not updated to account for this.
See 32be6020
> Fix test for missing appmetrics option

- README.md
tests are failing because of #15 
API docs are technically wrong (they are missing the authentication options), but that won't matter as soon as #11 lands
> Update README with basic API docs

- lib/appmetrics-dash.js
- package.json
Depends on #3 , and can't merge until node-report 2.1.0 is release: https://github.com/nodejs/node-report/issues/55#issuecomment-278674968
> Update node report

- public/js/gcChart.js
Bad variable naming caused an infinite loop when truncating data - fixed by correctly naming variable.
> Fix gcChart's infinite loop in data truncation

- LICENSE
- package.json
The project is already under this license, this simply adds a LICENSE
file for it so that it is easier for scanners to detect the license.
Closes #36
> add Apache License 2.0 LICENSE file

- lib/appmetrics-dash.js
- public/js/header.js
"Go To Documentation" could be displayed twice if the server restarted and the dashboard page was left open.
> Fix bug in doclink and change default title

- lib/appmetrics-dash.js
- test/test-http-inject-recursion.js
In the process of doing #44 , I found a recursion bug for some call patterns. This fixes, and adds a regression test.
> Auto-injection with HTTP should not recurse

- README.md
- lib/appmetrics-dash.js
I've updated the attach function to require appmetrics if the user hasn't supplied it.  Also added a simple example so this is clear in the docs.  Fixes issue #63
> Require appmetrics early so we get http data on attach

- .snyk
debug doesn't call the affected code path in ms that uses a Regex, so
isn't vulnerable to the Regex DoS.
> Ignore snyk false-positive on debug+ms

- package.json
This addresses a number of the snyk vulnerability warnings, remaining
will be fixed when https://github.com/socketio/socket.io-adapter/pull/52
and https://github.com/socketio/socket.io-emitter/pull/61 are published.
> deps: update socket.io to 2.x

- lib/appmetrics-dash.js
- package.json
- public/index.html
Use the "connected" message to re-send static data when the client confirms it's connected to avoid timing issues.
This fixes an issue with the environment page, profiling enablement and title that caused them to sometimes fail to be set.
This also resolves an issue with being unable to see generated node-report files or heap dumps.
> Re-send static data when the client confirms it's connected

- .snyk
With dependency updates, there is no longer any dependencies on the `ms` version that was triggering warnings.
> Remove unnecessary .snyk file

- public/index.html
Latest graphmetrics renames some of the poorly named variables and functions that were included in the i18n support with https://github.com/RuntimeTools/graphmetrics/pull/17 and reverts to loading translation files with a synchronous call in order to avoid using ajax to load javascript with https://github.com/RuntimeTools/graphmetrics/pull/18
Fullscreen graphs seems to have been broken by https://github.com/RuntimeTools/appmetrics-dash/commit/f39f3759cbf7dd7d7deb2c5a71769cb2cb0fd598 which accidentally removes the 'hideable' class from the divs for the graphs, this PR also fixes that.
> Move to latest graphmetrics and fix fullscreen graph breakage

- public/index.html
This just triggers a full refresh when a resize occurs since we need to recalculate the positions of all the rectangles on the flame graph not just resize the canvas it's drawn on.
> Resize fix

- lib/appmetrics-dash.js
- public/index.html
- test/ex-badly-behaved.js
Depends on https://github.com/RuntimeTools/graphmetrics/pull/23 
Works much better with https://github.com/RuntimeTools/appmetrics/pull/467, because without it values are truncated to integral milliseconds,  infrequently reported, and include epoll block times along with execution times.
> Add graph for loop metrics

- public/index.html
This change passes the appmetrics-dash path through to graphmetrics so that paths under there can be excluded from the top 5 response times.
This resolves issue #78
> Filter the dashboard from the top 5 http response times.

- public/index.html
This is necessary when proxying only part of the path to the node server.
I don't need credit as a contributor. Feel free to re-do this change in a new PR.
> Don't hardcode socket.io to the root of the path

- .travis.yml
- package.json
Due to a clash between appmetrics-dash and appmetrics-prometheus when trying to move up to appmetrics 4.0.0 on a minor version change I had to unpublish appmetrics-dash 3.5.0. (Lots of dependencies including generated node applications use semver major to define dependencies which meant that appmetrics-dash 3.5.0 would be pulled in automatically and if a project is also using appmetrics-prometheus then two conflicting versions of appmetrics are required).  So we need to do major version releases of appmetrics-dash and appmetrics-prometheus in order to pull in a major version release of appmetrics.
> Update version to 4.0.0

- .gitignore
- AUTHORS.md
- lib/appmetrics-dash.js
- test/test-middleware.js
- test/test-no-middleware.js
This PR enable users to pass a middleware along with `options` object.
If I want to protect the appmetrics dash, pass a middleware like:
```js
const options = {
...
middleware: (req, res, next)=>{
// do stuff to protect
return next()
}
...
}
attach(options);
```
> adds option to pass middleware

- REST-API.md
- lib/classes/collections.js
We have added the method to the summary table but not to the output of the REST API.
We need the method in the REST API output for exactly the same reasons.
The PR for the summary table was: https://github.com/RuntimeTools/appmetrics-dash/pull/153
> Add the method to the summary data in the collections API.

- AUTHORS.md
- public/index.html
Before this change, the relative path assumed that index.html is served from `/appmetrics-dash`. Which causes an error if the user specifies a custom path in the dash options.
Since socket.io is always served from `/appmetrics-dash`, we might as well refer to it in a fixed way here.
Fixes #160
> Absolute, non-configurable path to socket.io

- README.md
- Fix: There is no dash in the `nodereport` property.
- Elaboration: Since node reports list all sorts of server internals such as environment variables, people might be interested in knowing how to disable them for security reasons.
> [Docs] Fix and elaborate on nodereport option
