- README.md
- lib/appmetrics-dash.js
the default port was 3000 and this clashes with express.  Chamging to be 3001
> Portchange

- public/index.html
/to @RuntimeTools/appmetrics-collaborators 
/cc @rmg
> Use secure download links to prevent MITM attacks

- .eslintignore
- public/js/.eslintrc
- public/js/cpuChart.js
- public/js/cpuProcessGauge.js
- public/js/envTable.js
- public/js/eventLoopChart.js
- public/js/gauge.js
- public/js/gcChart.js
- public/js/header.js
- public/js/httpOutboundRequestsChart.js
- public/js/httpRequestsChart.js
- public/js/httpThroughPutChart.js
- public/js/httpTop5.js
- public/js/memChart.js
- public/js/memProcessGauge.js
- public/js/nodeReport.js
- public/js/probeEventsChart.js
since most changes are whitespace, diff best viewed as https://github.com/RuntimeTools/appmetrics-dash/pull/46/files?w=1
all other changes are just consistent use of of quotes, semi-colons, and removal of unused code
> eslint the public/js

- public/js/envTable.js
> Add tooltips to Environment data

- README.md
> Add title and docs to list of options

- lib/appmetrics-dash.js
- public/css/style2.css
- public/index.html
- public/js/nodeReport.js
> Add 'Generate Heap Snapshot' Button

- package.json
> deps: update express-basic-auth to 1.x

- package.json
Fixes https://github.com/RuntimeTools/appmetrics-dash/issues/79
> Appmetrics 3.x

- .gitignore
- public/css/style2.css
- public/index.html
This patch adds a menu button, a sliding menu and moves the
node-report and heapdump buttons onto the new menu.
> Add a menu button.

- .gitmodules
> Graphmetrics update

- lib/appmetrics-dash.js
- public/index.html
- public/profiling.js
Add code to parse Node.js profiler output into a form that can be displayed by graphmetrics as a flamegraph.
Add the ability to enable and disable the profiler.
Add the ability to clear the profiling data.
> Add the profiling tab.

- .eslintrc
- lib/appmetrics-dash.js
- public/profiling.js
This will clear all the linting errors from profiling.js
> Fix linting errors on profiling.js

- lib/appmetrics-dash.js
- package.json
- public/index.html
Includes a submodule update to pull in https://github.com/RuntimeTools/graphmetrics/pull/34
> HTTPS data in graphs

- lib/appmetrics-dash.js
This matches the data in Javametrics
> Add longest response time to aggregated http url data

- public/index.html
I've updated the index.html file with the new summary layout.
Tested on Chrome, Firefox and Safari.
> Updated index.html with new layout.

- lib/appmetrics-dash.js
- package.json
> Add HTTP verbs to URLs in summary table

- README.md
Add badges and information for LTS and commercial support
> Add LTS and Commercial Support info to README.md

- AUTHORS.md
- REST-API.md
- lib/appmetrics-rest.js
- lib/classes/collections.js
- test/test-rest-api.js
Resolves https://github.com/RuntimeTools/javametrics/issues/80 as part of work being done for https://github.ibm.com/dev-ex/portal/issues/412
> Add units data to the summary report

- public/index.html
Renders a dark theme at `/appmetrics-dash/?theme=dark`, plus a small tidy on default light theme.
These changes are inside the latest commit to graphmetrics, with some small changes also to `index.html` to allow for the switching of themes.
> Include latest graphmetrics with dark theme

- lib/appmetrics-dash.js
- package.json
- public/profiling.js
- test/apps/lb-3/package.json
This fixes vulnerabilities seen on the main github page.
> Update eslint to secure version
